### ISSUE TITLE
老哥，用不了

### ISSUE THREAD

**Issue by rmrf0621** [beijiyouyu/locoy-https#1]
![image](https://user-images.githubusercontent.com/67948373/98113474-ad0fd100-1ede-11eb-9ce1-88fbd46ec56e.png)

**Comment by beijiyouyu** [comment]
检查一下采集器中链接提取的规则设置是否正确，我在本地测试是正常的，看截图
![QQ截图20201105103754](https://user-images.githubusercontent.com/37782746/98191014-3eb92600-1f53-11eb-91e1-7f3990ffbc6c.png)
